# In your static/admin/config.yml file

backend:
  name: github
  repo: kstulgys/dev-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: Pages
    name: pages
    files:
      - label: Home Page
        name: home
        file: content/home.md
        fields:
          - { label: Me image, name: meImage, widget: image }
          - { label: Title, name: title, widget: string }
          - {
              label: Technologies,
              name: technologies,
              widget: list,
              allow_add: true,
            }
          - label: Projects
            name: projects
            widget: list
            allow_add: true
            fields:
              - label: Project
                name: project
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Image, name: image, widget: image }
                  - { label: Description, name: sescription, widget: markdown }
                  - {
                      label: "Tags",
                      name: "tags",
                      widget: list,
                      allow_add: true,
                      default: ["React"],
                    }
          - { label: About, name: about, widget: markdown }
            # options:
            # [
            #   "TypeScript",
            #   "JavaScript",
            #   "React",
            #   "Node",
            #   "GraphQL",
            #   "Gatsby",
            #   "Next",
            #   "MongoDB",
            #   "Firebase",
            #   "Prisma",
            #   "FaunaDB",
            #   "Apollo Client",
            #   "Apollo Server",
            #   "Headless CMS",
            #   "Jest",
            #   "Testing-library",
            #   "Redux",
            #   "CSS-in-JS",
            #   "GitHub",
            # ],
