# In your static/admin/config.yml file

backend:
  name: github
  repo: kstulgys/dev-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: markdown }
          - { label: Image, name: image, widget: image }
